using System;
using CssUI.CSS.Enums;
using CssUI.DOM;

namespace CssUI.CSS.BoxTree;

/// <summary>
/// Represents a marker box for a list item, generated by the ::marker pseudo-element.
/// Per CSS Lists 3 §3.1, the marker box is generated as the list item's first child,
/// before the ::before pseudo-element.
/// Spec: https://www.w3.org/TR/css-lists-3/#marker-pseudo
/// </summary>
/// <remarks>
/// The marker box contains content determined by (in order of priority):
/// 1. content property on ::marker (if not 'normal')
/// 2. list-style-image (if specified and valid)
/// 3. list-style-type (generates counter representation)
/// 4. Otherwise, no marker box is generated
/// </remarks>
public class CssMarkerBox : CssBox
{
    #region Properties
    /// <summary>
    /// The element that this marker box is associated with (the list item).
    /// </summary>
    private readonly WeakReference<Element>? _originatingElement;

    /// <summary>
    /// Gets the originating element (list item) for this marker box.
    /// </summary>
    public Element? OriginatingElement
    {
        get
        {
            if (_originatingElement?.TryGetTarget(out var element) == true)
            {
                return element;
            }
            return null;
        }
    }

    /// <summary>
    /// The position of this marker box relative to the list item.
    /// Per CSS Lists 3 §3.5, can be 'inside' or 'outside'.
    /// </summary>
    public EListStylePosition Position { get; private set; }

    /// <summary>
    /// The type of marker (disc, decimal, etc.) or none if using an image.
    /// </summary>
    public EListStyleType MarkerType { get; private set; }

    /// <summary>
    /// The marker string content to display.
    /// Generated from list-style-type counter representation or ::marker content property.
    /// </summary>
    public string MarkerString { get; private set; } = string.Empty;

    /// <summary>
    /// The counter value for this list item (1-based index in the list).
    /// Used for ordered list marker generation.
    /// </summary>
    public int CounterValue { get; private set; } = 1;
    #endregion

    #region Constructors
    /// <summary>
    /// Creates a marker box for a list item.
    /// </summary>
    /// <param name="originatingElement">The list item element this marker belongs to.</param>
    /// <param name="parent">The parent box (typically the principal box of the list item), or null if parenting is done separately.</param>
    public CssMarkerBox(Element originatingElement, CssBoxTreeNode? parent = null)
        : base(parent!)
    {
        _originatingElement = new WeakReference<Element>(originatingElement);

        // Marker boxes are inline-level per CSS Lists 3 §3.5 for inside markers
        // and block containers for outside markers
        DisplayType = new DisplayType(EOuterDisplayType.Inline, EInnerDisplayType.Flow);

        UpdateFromElement();
    }
    #endregion

    #region Methods
    /// <summary>
    /// Updates the marker box properties from the originating element's styles.
    /// </summary>
    public void UpdateFromElement()
    {
        var element = OriginatingElement;
        if (element?.Style is null)
        {
            return;
        }

        // Get list-style properties from the element
        var style = element.Style;

        // Get position - defaults to outside
        Position = style.ListStylePosition;

        // Get marker type - defaults to disc
        MarkerType = style.ListStyleType;

        // Update display type based on position
        // Per CSS Lists 3 §3.5: outside markers are block containers, inside markers are inline
        if (Position == EListStylePosition.Outside)
        {
            DisplayType = new DisplayType(EOuterDisplayType.Block, EInnerDisplayType.Flow_Root);
        }
        else
        {
            DisplayType = new DisplayType(EOuterDisplayType.Inline, EInnerDisplayType.Flow);
        }

        // Generate the marker string based on marker type and counter value
        MarkerString = GenerateMarkerString();
    }

    /// <summary>
    /// Sets the counter value for this marker (used for ordered lists).
    /// </summary>
    /// <param name="value">The 1-based counter value.</param>
    public void SetCounterValue(int value)
    {
        CounterValue = value;
        MarkerString = GenerateMarkerString();
    }

    /// <summary>
    /// Generates the marker string based on the list-style-type and counter value.
    /// </summary>
    private string GenerateMarkerString()
    {
        // Per CSS Lists 3 §3.2, marker content comes from:
        // 1. content on ::marker (not implemented yet)
        // 2. list-style-image (not implemented yet)
        // 3. list-style-type

        return MarkerType switch
        {
            EListStyleType.None => string.Empty,

            // Bullets (unordered)
            EListStyleType.Disc => "\u2022 ", // • (bullet)
            EListStyleType.Circle => "\u25CB ", // ○ (white circle)
            EListStyleType.Square => "\u25A0 ", // ■ (black square)

            // Numbers (ordered)
            EListStyleType.Decimal => $"{CounterValue}. ",
            EListStyleType.DecimalLeadingZero => $"{CounterValue:D2}. ",

            // Letters
            EListStyleType.LowerAlpha or EListStyleType.LowerLatin => $"{ToAlpha(CounterValue, lowercase: true)}. ",
            EListStyleType.UpperAlpha or EListStyleType.UpperLatin => $"{ToAlpha(CounterValue, lowercase: false)}. ",

            // Roman numerals
            EListStyleType.LowerRoman => $"{ToRoman(CounterValue).ToLowerInvariant()}. ",
            EListStyleType.UpperRoman => $"{ToRoman(CounterValue)}. ",

            // Greek
            EListStyleType.LowerGreek => $"{ToGreek(CounterValue)}. ",

            _ => string.Empty
        };
    }

    /// <summary>
    /// Converts a number to alphabetic representation (a, b, c, ... z, aa, ab, ...).
    /// </summary>
    private static string ToAlpha(int value, bool lowercase)
    {
        if (value < 1)
        {
            return value.ToString();
        }

        var result = new System.Text.StringBuilder();
        while (value > 0)
        {
            value--;
            char c = (char)((lowercase ? 'a' : 'A') + (value % 26));
            result.Insert(0, c);
            value /= 26;
        }
        return result.ToString();
    }

    /// <summary>
    /// Converts a number to Roman numeral representation.
    /// </summary>
    private static string ToRoman(int value)
    {
        if (value < 1 || value > 3999)
        {
            return value.ToString();
        }

        var result = new System.Text.StringBuilder();
        var romanNumerals = new (int Value, string Numeral)[]
        {
            (1000, "M"), (900, "CM"), (500, "D"), (400, "CD"),
            (100, "C"), (90, "XC"), (50, "L"), (40, "XL"),
            (10, "X"), (9, "IX"), (5, "V"), (4, "IV"), (1, "I")
        };

        foreach (var (romanValue, numeral) in romanNumerals)
        {
            while (value >= romanValue)
            {
                result.Append(numeral);
                value -= romanValue;
            }
        }
        return result.ToString();
    }

    /// <summary>
    /// Converts a number to lowercase Greek letter representation.
    /// </summary>
    private static string ToGreek(int value)
    {
        if (value < 1 || value > 24)
        {
            // Greek alphabet has 24 letters, fall back to decimal for larger values
            return value.ToString();
        }

        // Greek lowercase letters: α (alpha) starts at U+03B1
        return ((char)(0x03B1 + value - 1)).ToString();
    }
    #endregion
}
