using System;
using CssUI.CSS.Enums;
using CssUI.DOM;

namespace CssUI.CSS.BoxTree;

/// <summary>
/// Represents the table grid box generated by a table element (display: table).
/// Per CSS Display 3 §2.2, the table element generates two boxes:
/// 1. A table wrapper box (CssTableWrapperBox) - the principal box
/// 2. A table grid box (this class) - establishes a table formatting context
/// 
/// Spec: https://www.w3.org/TR/css-display-3/#valdef-display-table
/// Spec: https://www.w3.org/TR/css-tables-3/#table-grid-box
/// </summary>
/// <remarks>
/// The table grid box contains the table's internal structure (table-row-groups, table-rows, table-cells, etc.)
/// and establishes a table formatting context.
/// 
/// Per the spec:
/// - The table grid box is an additionally-generated box (not the principal box)
/// - It establishes a table formatting context
/// - It is a child of the table wrapper box
/// - Certain non-inherited properties (like 'border') apply to the grid box instead of the wrapper
/// 
/// Property Application (CSS Display 3 §1 + CSS Tables 3 §4):
/// Some table-specific properties apply to the grid box rather than the wrapper:
/// - border, border-spacing, border-collapse, border-*
/// - padding (applies to grid box)
/// - background properties apply to different layers
/// 
/// However, for simplicity in this implementation, we currently apply all properties at the
/// element level and let the layout algorithms determine which box they affect.
/// The grid box inherits from the wrapper box as needed.
/// </remarks>
public class CssTableGridBox : CssBox
{
    #region Properties
    /// <summary>
    /// The element that generates this table grid box (via its wrapper).
    /// </summary>
    private readonly WeakReference<Element>? _originatingElement;

    /// <summary>
    /// Gets the originating element for this table grid box.
    /// </summary>
    public Element? OriginatingElement
    {
        get
        {
            if (_originatingElement?.TryGetTarget(out var element) == true)
            {
                return element;
            }
            return null;
        }
    }

    /// <summary>
    /// The table wrapper box that this grid box is a child of.
    /// </summary>
    public CssTableWrapperBox? WrapperBox => parentNode as CssTableWrapperBox;
    #endregion

    #region Constructors
    /// <summary>
    /// Creates a table grid box as a child of a table wrapper box.
    /// </summary>
    /// <param name="originatingElement">The table element (display: table) that generates this grid.</param>
    /// <param name="parent">The table wrapper box that is the parent, or null if parenting is done separately.</param>
    public CssTableGridBox(Element originatingElement, CssBoxTreeNode? parent = null)
        : base(parent!)
    {
        _originatingElement = new WeakReference<Element>(originatingElement);

        // Table grid box establishes a table formatting context
        // Per CSS Display 3 §2.2: "...and which contains an additionally-generated table grid box
        // that establishes a table formatting context."
        // The grid box has display type 'table' (not to be confused with the CSS property value)
        DisplayType = new DisplayType(EOuterDisplayType.Block, EInnerDisplayType.Table);
    }
    #endregion

    #region Methods
    /// <summary>
    /// Returns a string representation for debugging.
    /// </summary>
    public override string ToString()
    {
        var element = OriginatingElement;
        var tagName = element?.tagName ?? "?";
        return $"TableGridBox[{tagName}]";
    }
    #endregion
}
