using System;
using CssUI.CSS.Enums;
using CssUI.DOM;

namespace CssUI.CSS.BoxTree;

/// <summary>
/// Represents the principal box generated by a table element (display: table).
/// Per CSS Display 3 §2.2, the table element generates TWO boxes:
/// 1. A table wrapper box (this class) - the principal box that establishes a block formatting context
/// 2. A table grid box (CssTableGridBox) - contains the table's internal structure and establishes a table formatting context
/// 
/// Spec: https://www.w3.org/TR/css-display-3/#valdef-display-table
/// Spec: https://www.w3.org/TR/css-tables-3/#table-wrapper-box
/// </summary>
/// <remarks>
/// The table wrapper box serves as the containing block for caption boxes and the table grid box.
/// 
/// Per the spec:
/// - The table wrapper box has outer display type 'block' (blockifies if inline-table)
/// - The table wrapper box establishes a new block formatting context
/// - The table grid box is generated as a child of the wrapper
/// - Inherited properties are assigned to the wrapper box and inherit through to grid box
/// - Non-inherited properties default to applying to the wrapper, but some (like 'border')
///   are defined to apply to the grid box instead
/// 
/// Property Application (CSS Display 3 §1):
/// "Boxes are assigned the same styles as their generating element, unless otherwise indicated.
/// In general, inherited properties are assigned to the principal box, and then inherit through
/// the box tree to any other boxes generated by the same element. Non-inherited properties default
/// to applying to the principal box, but when the element generates multiple boxes, are sometimes
/// defined to apply to a different box: for example, the 'border' properties applied to a table
/// element are applied to its table grid box, not to its principal table wrapper box."
/// </remarks>
public class CssTableWrapperBox : CssPrincipalBox
{
    #region Properties
    /// <summary>
    /// The element that generates this table wrapper box.
    /// </summary>
    private readonly WeakReference<Element>? _originatingElement;

    /// <summary>
    /// Gets the originating element for this table wrapper box.
    /// </summary>
    public Element? OriginatingElement
    {
        get
        {
            if (_originatingElement?.TryGetTarget(out var element) == true)
            {
                return element;
            }
            return null;
        }
    }

    /// <summary>
    /// The table grid box generated as a child of this wrapper.
    /// </summary>
    public CssTableGridBox? GridBox { get; private set; }

    /// <summary>
    /// Override DisplayType to return the wrapper's display type (block/flow-root)
    /// instead of the element's display type (table).
    /// Per CSS Display 3 §2.2: The wrapper establishes a block formatting context.
    /// </summary>
    public override DisplayType DisplayType => new DisplayType(EOuterDisplayType.Block, EInnerDisplayType.Flow_Root);
    #endregion

    #region Constructors
    /// <summary>
    /// Creates a table wrapper box for a table element.
    /// </summary>
    /// <param name="originatingElement">The table element (display: table) that generates this wrapper.</param>
    /// <param name="parent">The parent box, or null if parenting is done separately.</param>
    public CssTableWrapperBox(Element originatingElement, CssBoxTreeNode? parent = null)
        : base(originatingElement, parent!)
    {
        _originatingElement = new WeakReference<Element>(originatingElement);
        // DisplayType is overridden by the property to return Flow_Root
    }
    #endregion

    #region Methods
    /// <summary>
    /// Sets the table grid box that is the child of this wrapper.
    /// This should only be called during box generation.
    /// </summary>
    /// <param name="gridBox">The table grid box.</param>
    internal void SetGridBox(CssTableGridBox gridBox)
    {
        GridBox = gridBox;
    }

    /// <summary>
    /// Returns a string representation for debugging.
    /// </summary>
    public override string ToString()
    {
        var element = OriginatingElement;
        var tagName = element?.tagName ?? "?";
        return $"TableWrapperBox[{tagName}]";
    }
    #endregion
}
