<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>12.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <Configurations>Debug;Release;CssUI - Debug;CssUI - Release;Core - Debug;Core - Release</Configurations>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <!-- Make internals visible to test project -->
  <ItemGroup>
    <InternalsVisibleTo Include="CssUITests" />
  </ItemGroup>

  <!-- Default Debug configuration - includes HTML support -->
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>DEBUG;TRACE;WINDOWS;ENABLE_HTML</DefineConstants>
    <Optimize>false</Optimize>
  </PropertyGroup>

  <!-- Default Release configuration - includes HTML support -->
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DefineConstants>TRACE;WINDOWS;ENABLE_HTML</DefineConstants>
    <Optimize>true</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Core - Debug|AnyCPU'">
    <DefineConstants>DEBUG;TRACE;WINDOWS;ENABLE_HEADLESS;DISABLE_FONT_SYSTEM</DefineConstants>
    <DocumentationFile></DocumentationFile>
    <Optimize>false</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Core - Release|AnyCPU'">
    <DefineConstants>TRACE;WINDOWS;ENABLE_HEADLESS;DISABLE_FONT_SYSTEM </DefineConstants>
    <DocumentationFile>G:\CODE\CssUI\CssUI\CssUI.Core.xml</DocumentationFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='CssUI - Debug|AnyCPU'">
    <DefineConstants>TRACE;WINDOWS;ENABLE_HTML; </DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='CssUI - Release|AnyCPU'">
    <DefineConstants>TRACE;WINDOWS;ENABLE_HTML; </DefineConstants>
    <DocumentationFile>G:\CODE\CssUI\CssUI\CssUI.xml</DocumentationFile>
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.2" />
  </ItemGroup>

  <ItemGroup Condition="!$(DefineConstants.Contains('ENABLE_HTML'))">
    <Compile Remove="HTML\**" />
    <EmbeddedResource Remove="HTML\**" />
    <None Remove="HTML\**" />
  </ItemGroup>

  <ItemGroup Condition="$(DefineConstants.Contains('DISABLE_FONT_SYSTEM'))">
    <Compile Remove="Fonts\Core\**" />
    <EmbeddedResource Remove="Fonts\Core\**" />
    <None Remove="Fonts\Core\**" />

    <Compile Remove="Fonts\Types\**" />
    <EmbeddedResource Remove="Fonts\Types\**" />
    <None Remove="Fonts\Types\**" />
  </ItemGroup>

  <!-- SixLabors packages removed - implementations moved to separate project -->

  <!-- Legacy CSS/Layouts folder deleted - used defunct types (cssElement, IParentElement) -->
  <!-- Flex/Grid layout algorithms are now in CSS/Formatting/ using the box tree system -->

  <ItemGroup>
    <Compile Remove="Common\EElementTag.cs" />
    <Compile Remove="Common\EnumTables.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Common\EElementTag.tt" />
    <None Remove="Common\EnumTables.tt" />
    <None Remove="HTML\Common\HTMLElementTable.tt" />
  </ItemGroup>

  <ItemGroup>
    <None Include="CORE\Localization\ISO-639\Enum_ISO639.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Enum_ISO639.tt</DependentUpon>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Common\Exceptions\ParserErrors.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ParserErrors.resx</DependentUpon>
    </Compile>
    <Compile Update="CORE\Localization\ISO-639\Enum_ISO639.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Enum_ISO639.tt</DependentUpon>
    </Compile>
    <Compile Update="CORE\Localization\ISO-15924\EISO_15924.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>EISO_15924.tt</DependentUpon>
    </Compile>
    <Compile Update="CSS\Exceptions\CssErrors.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>CssErrors.resx</DependentUpon>
    </Compile>
    <Compile Update="ExceptionMessages.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ExceptionMessages.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="CORE\Localization\ISO-639\Enum_ISO639.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>Enum_ISO639.cs</LastGenOutput>
    </None>
    <None Update="CORE\Localization\ISO-15924\EISO_15924.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>EISO_15924.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="CORE\Debug\" />
    <Folder Include="CORE\Units\Interface\" />
    <Folder Include="DOM\Base\" />
    <Folder Include="CORE\Structs\" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Common\Exceptions\ParserErrors.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>ParserErrors.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="CSS\Exceptions\CssErrors.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>CssErrors.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="ExceptionMessages.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>ExceptionMessages.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
