//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CssUI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CssUI.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This attribute&apos;s type does not match the one requested.
        /// </summary>
        internal static string ERROR_Attribute_Type_Mismatch {
            get {
                return ResourceManager.GetString("ERROR_Attribute_Type_Mismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A node which contains another cannot be inserted into the node it contains.
        /// </summary>
        internal static string ERROR_Cannot_Insert_Node_Due_To_Recursion {
            get {
                return ResourceManager.GetString("ERROR_Cannot_Insert_Node_Due_To_Recursion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidValue: formtarget cannot accept the value: \&quot;{0}\&quot;.
        /// </summary>
        internal static string ERROR_FormTarget_Invalid_Value {
            get {
                return ResourceManager.GetString("ERROR_FormTarget_Invalid_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The only valid value for this type of input element is an empty string.
        /// </summary>
        internal static string ERROR_InputElement_InputType_Value_Must_Be_Empty {
            get {
                return ResourceManager.GetString("ERROR_InputElement_InputType_Value_Must_Be_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This attribute cannot be specified for an input element of this type({0}).
        /// </summary>
        internal static string ERROR_InputElement_Invalid_Attribute {
            get {
                return ResourceManager.GetString("ERROR_InputElement_Invalid_Attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start cannot be greater than end.
        /// </summary>
        internal static string ERROR_InputElement_InvalidValue_Start_Greater_Than_End {
            get {
                return ResourceManager.GetString("ERROR_InputElement_InvalidValue_Start_Greater_Than_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input-type({0}) does not implement this method.
        /// </summary>
        internal static string ERROR_InputElement_Method_Unsupported_By_InputType {
            get {
                return ResourceManager.GetString("ERROR_InputElement_Method_Unsupported_By_InputType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input element has no allowed-value-step, step cannot be \&quot;any\&quot;.
        /// </summary>
        internal static string ERROR_InputElement_Missing_Allowed_Value_Step {
            get {
                return ResourceManager.GetString("ERROR_InputElement_Missing_Allowed_Value_Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This property is not valid for input elements of type \&quot;{0}\&quot;.
        /// </summary>
        internal static string ERROR_InputElement_Property_Unsupported_By_InputType {
            get {
                return ResourceManager.GetString("ERROR_InputElement_Property_Unsupported_By_InputType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input-type({0}) value cannot be converted to the requested type.
        /// </summary>
        internal static string ERROR_InputElement_Value_Cannot_Convert {
            get {
                return ResourceManager.GetString("ERROR_InputElement_Value_Cannot_Convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be infinity.
        /// </summary>
        internal static string ERROR_Invalid_Value_Infinity {
            get {
                return ResourceManager.GetString("ERROR_Invalid_Value_Infinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloning logic for this node type has not been implemented.
        /// </summary>
        internal static string ERROR_Node_No_Cloning_Logic {
            get {
                return ResourceManager.GetString("ERROR_Node_No_Cloning_Logic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This parent node is not a valid type.
        /// </summary>
        internal static string ERROR_Node_Parent_Type_Invalid {
            get {
                return ResourceManager.GetString("ERROR_Node_Parent_Type_Invalid", resourceCulture);
            }
        }
    }
}
