using CssUI.DOM.Internal;

namespace CssUI.DOM.Events
{
    [DomEnum]
    public enum EEventType : uint
    {
        [DomKeyword("")]
        None = 0x0,
        [DomKeyword("abort")]
        abort,
        [DomKeyword("auxclick")]
        auxclick,
        [DomKeyword("blur")]
        blur,
        [DomKeyword("cancel")]
        cancel,
        [DomKeyword("canplay")]
        canplay,
        [DomKeyword("canplaythrough")]
        canplaythrough,
        [DomKeyword("change")]
        change,
        [DomKeyword("click")]
        click,
        [DomKeyword("close")]
        close,
        [DomKeyword("contextmenu")]
        contextmenu,
        [DomKeyword("cuechange")]
        cuechange,
        [DomKeyword("dblclick")]
        dblclick,
        [DomKeyword("drag")]
        drag,
        [DomKeyword("dragend")]
        dragend,
        [DomKeyword("dragenter")]
        dragenter,
        [DomKeyword("dragexit")]
        dragexit,
        [DomKeyword("dragleave")]
        dragleave,
        [DomKeyword("dragover")]
        dragover,
        [DomKeyword("dragstart")]
        dragstart,
        [DomKeyword("drop")]
        drop,
        [DomKeyword("durationchange")]
        durationchange,
        [DomKeyword("emptied")]
        emptied,
        [DomKeyword("ended")]
        ended,
        [DomKeyword("focus")]
        focus,
        [DomKeyword("formdata")]
        formdata,
        [DomKeyword("input")]
        input,
        [DomKeyword("invalid")]
        invalid,
        [DomKeyword("keydown")]
        keydown,
        [DomKeyword("keypress")]
        keypress,
        [DomKeyword("keyup")]
        keyup,
        [DomKeyword("load")]
        load,
        [DomKeyword("loadeddata")]
        loadeddata,
        [DomKeyword("loadedmetadata")]
        loadedmetadata,
        [DomKeyword("loadend")]
        loadend,
        [DomKeyword("loadstart")]
        loadstart,
        [DomKeyword("mousedown")]
        mousedown,
        [DomKeyword("mouseenter")]
        mouseenter,
        [DomKeyword("mouseleave")]
        mouseleave,
        [DomKeyword("mousemove")]
        mousemove,
        [DomKeyword("mouseout")]
        mouseout,
        [DomKeyword("mouseover")]
        mouseover,
        [DomKeyword("mouseup")]
        mouseup,
        [DomKeyword("wheel")]
        wheel,
        [DomKeyword("pause")]
        pause,
        [DomKeyword("play")]
        play,
        [DomKeyword("playing")]
        playing,
        [DomKeyword("progress")]
        progress,
        [DomKeyword("ratechange")]
        ratechange,
        [DomKeyword("reset")]
        reset,
        [DomKeyword("resize")]
        resize,
        [DomKeyword("scroll")]
        scroll,
        [DomKeyword("securitypolicyviolation")]
        securitypolicyviolation,
        [DomKeyword("seeked")]
        seeked,
        [DomKeyword("seeking")]
        seeking,
        [DomKeyword("select")]
        select,
        [DomKeyword("stalled")]
        stalled,
        [DomKeyword("submit")]
        submit,
        [DomKeyword("suspend")]
        suspend,
        [DomKeyword("timeupdate")]
        timeupdate,
        [DomKeyword("toggle")]
        toggle,
        [DomKeyword("volumechange")]
        volumechange,
        [DomKeyword("waiting")]
        waiting,

        [DomKeyword("selectstart")]
        selectstart,
        [DomKeyword("selectionchange")]
        selectionchange,
        
        [DomKeyword("copy")]
        copy,
        [DomKeyword("cut")]
        cut,
        [DomKeyword("paste")]
        paste,

        [DomKeyword("hashchange")]
        hashchange,
        [DomKeyword("languagechange")]
        languagechange,
        [DomKeyword("message")]
        message,
        [DomKeyword("messageerror")]
        messageerror,
        [DomKeyword("offline")]
        offline,
        [DomKeyword("online")]
        online,
        [DomKeyword("pagehide")]
        pagehide,
        [DomKeyword("pageshow")]
        pageshow,
        [DomKeyword("popstate")]
        popstate,
        [DomKeyword("rejectionhandled")]
        rejectionhandled,
        [DomKeyword("storage")]
        storage,
        [DomKeyword("unhandledrejection")]
        unhandledrejection,
    }
}
