//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CssUI.CSS.Exceptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CssErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CssErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CssUI.CSS.Exceptions.CssErrors", typeof(CssErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to consume component value.
        /// </summary>
        internal static string CANT_CONSUME_COMPONENT_VALUE {
            get {
                return ResourceManager.GetString("CANT_CONSUME_COMPONENT_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to consume decleration.
        /// </summary>
        internal static string CANT_CONSUME_DECLERATION {
            get {
                return ResourceManager.GetString("CANT_CONSUME_DECLERATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to consume qualified rule.
        /// </summary>
        internal static string CANT_CONSUME_QUALIFIED_RULE {
            get {
                return ResourceManager.GetString("CANT_CONSUME_QUALIFIED_RULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expecting EOF.
        /// </summary>
        internal static string EOF_EXPECTED {
            get {
                return ResourceManager.GetString("EOF_EXPECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expecting combinator token.
        /// </summary>
        internal static string EXPECTING_COMBINATOR {
            get {
                return ResourceManager.GetString("EXPECTING_COMBINATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expecting comparator token.
        /// </summary>
        internal static string EXPECTING_COMPARATOR {
            get {
                return ResourceManager.GetString("EXPECTING_COMPARATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expecting function name token.
        /// </summary>
        internal static string EXPECTING_FUNCTION_NAME_TOKEN {
            get {
                return ResourceManager.GetString("EXPECTING_FUNCTION_NAME_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expecting ident token.
        /// </summary>
        internal static string EXPECTING_IDENT {
            get {
                return ResourceManager.GetString("EXPECTING_IDENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expecting start of media condition.
        /// </summary>
        internal static string EXPECTING_MEDIA_CONDITION_START {
            get {
                return ResourceManager.GetString("EXPECTING_MEDIA_CONDITION_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expecting opening parentheses.
        /// </summary>
        internal static string EXPECTING_OPENING_PARENTHESES {
            get {
                return ResourceManager.GetString("EXPECTING_OPENING_PARENTHESES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expecting start of simple block.
        /// </summary>
        internal static string EXPECTING_SIMPLE_BLOCK_START {
            get {
                return ResourceManager.GetString("EXPECTING_SIMPLE_BLOCK_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized combinator keyword &quot;{0}&quot;.
        /// </summary>
        internal static string INVALID_COMBINATOR {
            get {
                return ResourceManager.GetString("INVALID_COMBINATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized media type: &quot;{0}&quot;.
        /// </summary>
        internal static string INVALID_MEDIA_TYPE {
            get {
                return ResourceManager.GetString("INVALID_MEDIA_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is invalid to mix &apos;and&apos; and &apos;or&apos; and &apos;not&apos; at the same level of a media query. please enclose the condition in parentheses.
        /// </summary>
        internal static string INVALID_MULTIPLE_COMBINATORS_ON_MEDIARULE {
            get {
                return ResourceManager.GetString("INVALID_MULTIPLE_COMBINATORS_ON_MEDIARULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream is NULL.
        /// </summary>
        internal static string STREAM_IS_NULL {
            get {
                return ResourceManager.GetString("STREAM_IS_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected EOF.
        /// </summary>
        internal static string UNEXPECTED_EOF {
            get {
                return ResourceManager.GetString("UNEXPECTED_EOF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected token.
        /// </summary>
        internal static string UNEXPECTED_TOKEN {
            get {
                return ResourceManager.GetString("UNEXPECTED_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled token type cannot be interpreted as css-value: \&quot;{0}\&quot;.
        /// </summary>
        internal static string UNHANDLED_TOKEN_FOR_CSS_VALUE {
            get {
                return ResourceManager.GetString("UNHANDLED_TOKEN_FOR_CSS_VALUE", resourceCulture);
            }
        }
    }
}
